export const USER_LOGIN_REQUEST="USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL="USER_LOGIN_FAIL";

export const USER_DATA_LOADING="USER_DATA_LOADING";
export const USER_DATA_FOUND="USER_DATA_FOUND";
export const USER_DATA_NOTFOUND="USER_DATA_NOTFOUND";

export const SUGGESTED_PROFILE_LOADING="SUGGESTED_PROFILE_LOADING";
export const SUGGESTED_PROFILE_SUCCESS="SUGGESTED_PROFILE_SUCCESS";
export const SUGGESTED_PROFILE_FAIL="SUGGESTED_PROFILE_FAIL";

export const USER_AUTH_STATE_CHANGE="USER_AUTH_STATE_CHANGE";

export const REDIRECT_USER_TOEDIT="REDIRECT_USER_TOEDIT";

export const CLEAR_ERROR="CLEAR_ERROR";
